In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
d=load_breast_cancer()

In [4]:
d.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
d.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
d.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
d.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
df=pd.DataFrame(np.c_[d.data,d.target],columns=[list(d.feature_names)+['target']])

In [9]:
df

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
0                  0.07871  ...         17.33          184.60     2019.0   
1                  0.05667  ...         23.41          158.80     1956.0   
2                  0.05999  ...         25.53          152.50     1709.0   
3                  0.09744  ...         26.50           98.87      567.7   
4                  0.05883  ...         16.67          152.20     1575.0   
..                     ...  ...           ...             ...        ...   
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
0            0.16220           0.66560          0.7119               0.2654   
1            0.12380           0.18660          0.2416               0.1860   
2            0.14440           0.42450          0.4504               0.2430   
3            0.20980           0.86630          0.6869               0.2575   
4            0.13740           0.20500          0.4000               0.1625   
..               ...               ...             ...                  ...   
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
0           0.4601                 0.11890    0.0  
1           0.2750                 0.08902    0.0  
2           0.3613                 0.08758    0.0  
3           0.6638                 0.17300    0.0  
4           0.2364                 0.07678    0.0  
..             ...                     ...    ...  
564         0.2060      

In [10]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [11]:
df.tail()

mean radius mean texture mean perimeter mean area mean smoothness  \
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
564         0.2060                 0.07115    0.0  
565         0.2572                 0.06637    0.0  
566         0.2218                 0.07820    0.0  
567         0.4087                 0.12400    0.0  
568         0.2871                 0.07039    1.0  

[5 rows x 31 columns]

In [12]:
df.shape

(569, 31)

In [13]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=2020)

In [15]:
print('shape of x_train=',x_train.shape) 
print('shape of y_train=',y_train.shape)
print('shape of x_test=',x_test.shape) 
print('shape of y_test=',y_test.shape)

shape of x_train= (455, 30)
shape of y_train= (455,)
shape of x_test= (114, 30)
shape of y_test= (114,)


In [16]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='gini')
classifier.fit(x_train,y_train)
classifier.score(x_test,y_test)

0.9298245614035088

In [17]:
classifier=DecisionTreeClassifier(criterion='entropy')
classifier.fit(x_train,y_train)
classifier.score(x_test,y_test)

0.9385964912280702

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train_sc=sc.transform(x_train)
x_test_sc=sc.transform(x_test)

In [19]:
classifier_sc=DecisionTreeClassifier(criterion='gini')
classifier_sc.fit(x_train_sc,y_train)
classifier_sc.score(x_test_sc,y_test)

0.9473684210526315

In [20]:
classifier_sc=DecisionTreeClassifier(criterion='entropy')
classifier_sc.fit(x_train_sc,y_train)
classifier_sc.score(x_test_sc,y_test)

0.9210526315789473

In [21]:
patient1=[17.9,10.38,122.8,1001.0,.1184,.2776,.3001,.1471,.2419,.07871,1.095,.9053,8.589,
          153.4,.006399,.04904,.05373,.01587,.03003,.006193,25.38,17.33,184.6,2019.0,.1622,.6656,.7119,.2654,.4601,.1189]
patient1=np.array([patient1])
patient1

array([[1.790e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [22]:
pred=classifier_sc.predict(patient1)
if pred[0]==0:
    print("cancer")
else:
    print("not cancer")

cancer


In [23]:
x_train

mean radius mean texture mean perimeter mean area mean smoothness  \
215       13.86        16.93          90.96     578.9         0.10260   
460       17.08        27.15         111.20     930.9         0.09898   
540       11.54        14.44          74.65     402.9         0.09984   
270       14.29        16.82          90.30     632.6         0.06429   
357       13.87        16.21          88.52     593.7         0.08743   
..          ...          ...            ...       ...             ...   
560       14.05        27.15          91.38     600.4         0.09929   
157       16.84        19.46         108.40     880.2         0.07445   
91        15.37        22.76         100.20     728.2         0.09200   
323       20.34        21.51         135.90    1264.0         0.11700   
392       15.49        19.97         102.40     744.7         0.11600   

    mean compactness mean concavity mean concave points mean symmetry  \
215          0.15170        0.09901             0.05602        0.2106   
460          0.11100        0.10070             0.06431        0.1793   
540          0.11200        0.06737             0.02594        0.1818   
270          0.02675        0.00725             0.00625        0.1508   
357          0.05492        0.01502             0.02088        0.1424   
..               ...            ...                 ...           ...   
560          0.11260        0.04462             0.04304        0.1537   
157          0.07223        0.05150             0.02771        0.1844   
91           0.10360        0.11220             0.07483        0.1717   
323          0.18750        0.25650             0.15040        0.2569   
392          0.15620        0.18910             0.09113        0.1929   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
215                0.06916  ...        15.75         26.93          104.40   
460                0.06281  ...        22.96         34.49          152.10   
540                0.06782  ...        12.26         19.68           78.78   
270                0.05376  ...        14.91         20.65           94.44   
357                0.05883  ...        15.11         25.58           96.74   
..                     ...  ...          ...           ...             ...   
560                0.06171  ...        15.30         33.17          100.20   
157                0.05268  ...        18.22         28.07          120.30   
91                 0.06097  ...        16.43         25.84          107.50   
323                0.06670  ...        25.30         31.86          171.10   
392                0.06744  ...        21.20         29.41          142.10   

    worst area worst smoothness worst compactness worst concavity  \
215      750.1          0.14600           0.43700         0.46360   
460     1648.0          0.16000           0.24440         0.26390   
540      457.8          0.13450           0.21180         0.17970   
270      684.6          0.08567           0.05036         0.03866   
357      694.4          0.11530           0.10080         0.05285   
..         ...              ...               ...             ...   
560      706.7          0.12410           0.22640         0.13260   
157     1032.0          0.08774           0.17100         0.18820   
91       830.9          0.12570           0.19970         0.28460   
323     1938.0          0.15920           0.44920         0.53440   
392     1359.0          0.16810           0.39130         0.55530   

    worst concave points worst symmetry worst fractal dimension  
215              0.16540         0.3630                 0.10590  
460              0.15550         0.3010                 0.09060  
540              0.06918         0.2329                 0.08134  
270              0.03333         0.2458                 0.06120  
357              0.05556         0.2362                 0.07113  
..                   ...            ...                     ...  
560              0.104

In [24]:
x_train_sc

array([[-0.05370575, -0.53417092, -0.01761448, ...,  0.81908207,
         1.25062232,  1.33518276],
       [ 0.87820818,  1.81956841,  0.83154698, ...,  0.6641822 ,
         0.21864042,  0.42970317],
       [-0.72514684, -1.10763578, -0.7018943 , ..., -0.68641949,
        -0.91487518, -0.11831912],
       ...,
       [ 0.38330979,  0.80851991,  0.37004618, ...,  0.54057523,
        -0.53703665, -0.89123177],
       [ 1.82169868,  0.52063594,  1.86782604, ...,  2.43223121,
         4.45975313,  1.12804691],
       [ 0.4180395 ,  0.16596289,  0.46234634, ...,  1.54977135,
         0.51325461,  1.09845607]])